services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: piar_backend
    environment:
      - DATABASE_URL=sqlite:///./data/piar.db
      - SECRET_KEY=change_this_in_production_secret_key
    volumes:
      - piar_data:/app/data
    ports:
      - "8000:8000"
    networks:
      - piar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: piar_frontend
    environment:
      - VITE_API_URL=/api
    ports:
      - "8587:80"
    depends_on:
      - backend
    networks:
      - piar-network

networks:
  piar-network:
    driver: bridge

volumes:
  piar_data:
